baseurl = "https://sylvaindenyse.me"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = false

[params]
    author = "Sylvain DENYSE"
    avatarurl = "/img/avatar.jpg"

    favicon_32 = "/favicon-32x32.png"
    favicon_16 = "/favicon-16x16.png"
    favicon = "/favicon.ico"
    manifest = "/manifest.json"
    
    hidecredits = true
    hidecopyright = false

    rtl = false

    math = false
    custom_css = ["/css/custom.css"]

[languages]
    [languages.en]
        languagename = "English" 
        title = "Sylvain DENYSE - Web Developer Designer"
        footercontent = "Innovating with respect."

        [languages.en.params]
        info = "Full Stack, DevOps and Magician"
        description = "Sylvain DENYSE's personal website"
        keywords = "blog,developer,personal"

        [languages.en.menu]
            [[languages.en.menu.main]]
            name = "More information"
            weight = 1
            url = "/more/"
    
    [languages.fr]
        languagename = "Français" 
        title = "Sylvain DENYSE | Concepteur Developpeur Web"
        footercontent = "Innover dans le respect."

        [languages.fr.params]
        info = "Full Stack, DevOps et Magicien"
        description = "Site web personnel de Sylvain DENYSE"
        keywords = "blog,developpeur,personnel"

        [languages.fr.menu]
            [[languages.fr.menu.main]]
            name = "En savoir plus"
            weight = 1
            url = "/more/"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/sylvaindns/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com//sylvainDNS/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/sylvaindenyse/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/sylvain-denyse/"
